version: '3'
services:
  ecommerce-concept-db:
    container_name: E-commerce-concept-Postgres
    platform: linux/arm64
    image: timescale/timescaledb:latest-pg15
    restart: always
    ports:
      - '${DB_PORT}:5440'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: '${DB_NAME}'
    volumes:
      - ecommerce-concept-db-volume:/var/lib/postgresql/data

volumes:
  ecommerce-concept-db-volume:
