version: '3'
services:
  e-commerce-concept:
    container_name: E-commerce-concept
    platform: linux/amd64
    image: mysql
    restart: always
    ports:
      - '5445:3306'
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - e-commerce-concept-volume:/var/lib/mysql

volumes:
  e-commerce-concept-volume:
